server:
  port: 9000


spring:
  cloud:
    service-registry:
      auto-registration:
        enabled: true
  application:
    name: CLIENT_1


eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
#      defaultZone: http://lwh2.com:8888/eureka/
      defaultZone: http://localhost:8888/eureka/
  instance:
    non-secure-port-enabled: true
    metadata-map:
      one: this is one
    lease-renewal-interval-in-seconds: 300
management:
  endpoints:
    web:
      exposure:
        include: '*'
